### ISSUE TITLE
Gadgetron state in electron

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/GadgetronControl#10]
- wrong state description "started with main.js"

**Comment by chrisdecker1201** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/20707614/23589382/3c1b3332-01cc-11e7-8ef9-4e1ab9630dea.png)

**Comment by thomaskuestner** [comment]
solved with https://github.com/thomaskuestner/GadgetronControl/commit/1c38ff29b61ff48f8d503a1fe6a4531d258fa77f
