### ISSUE TITLE
UI_local

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/GadgetronControl#11]
remove UI_local from config file and set automatically for:
npm run remote -> UI_local = false
npm start -> UI_local = true

**Comment by chrisdecker1201** [comment]
I've checking now in the uploadDialog if we started the app in electron or not.
https://github.com/electron/electron/issues/2288
Maybe you can verify if it's working and close this issue.

**Comment by thomaskuestner** [comment]
Solved with https://github.com/thomaskuestner/GadgetronControl/commit/84fa1baf162be9f5a30f6e3aa551a0e20d0ddce2
