### ISSUE TITLE
Open file dialog in electron

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/GadgetronControl#13]
forwarding of file dialog in api/electronAPI.js failing
`const mainProcess = remote.require('./../main');`

**Comment by chrisdecker1201** [comment]
The child_process.fork() method is a special case of child_process.spawn() used specifically to spawn new Node.js processes. Like child_process.spawn(), a ChildProcess object is returned. The returned ChildProcess will have an additional communication channel built-in that allows messages to be passed back and forth between the parent and child. See child.send() for details.

I think we'll need this communication channel.

**Comment by thomaskuestner** [comment]
Thanks for the hint. I think you are right. So we have to wrap an IPC channel around respectively inside the JSON api call.

**Comment by thomaskuestner** [comment]
solved with https://github.com/thomaskuestner/GadgetronControl/commit/cfabc8fcb2545a652c95f3ad28763558d729e572
