### ISSUE TITLE
Gadgetron state

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/GadgetronControl#7]
- automatically retrieve gadgetron port -> remove from config
- start/restart Gadgetron server on button click with predefined settings and output redirect

**Comment by chrisdecker1201** [comment]
first point solved with 7ac0f2563ea37d8252ed0a749ec473609ef44feb

**Comment by thomaskuestner** [comment]
see: https://github.com/gadgetron/gadgetron/blob/master/apps/gadgetron/webapp/gadgetron_web_app.py
for point 2

**Comment by thomaskuestner** [comment]
- automatically start gadgetron server if not running in background already
- include process id of gadgetron server to state tag
